server:
  port: 4005

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:4004
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: Limiting-service-route
          uri: http://limiting-service:4001
          predicates:
            - Path=/lim/**
          filters:
            - AuthValidation
            - StripPrefix=1

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs

      - name: Limiting Service
        url: /lim/v3/api-docs

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG
    reactor.netty: DEBUG